import { Footer } from "./_components/shared/Footer";
import { Roboto } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.variable}flex flex-col`}>
        {/* <Header /> */}
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
