import { FaBitcoin, FaEthereum } from "react-icons/fa";
import { SiBinance } from "react-icons/si";

export const cryptoData = [
  {
    icon: <FaBitcoin className="text-[#F7931A] size-8" />,
    name: "BTC",
    fullName: "Bitcoin",
    price: "$98,623.51",
    change: "+4.08%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <FaEthereum className="text-[#627EEA] size-8" />,
    name: "ETH",
    fullName: "Ethereum",
    price: "$3,489.55",
    change: "+2.16%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
  {
    icon: <SiBinance className="text-[#F3BA2F] size-8" />,
    name: "BNB",
    fullName: "BNB Smart Chain",
    price: "$696.52",
    change: "+0.40%",
    amount: "0",
    value: "$0.00",
  },
];
